auto: true
server: true
permalink: /:title/
url: /~adriansieber/schiff

allgemeines:
    - Allgemeines
    - Bodensee
    - Wetterkunde
    - Navigation
    - Ausrüstung
    - Anker
    - Schifffahrtszeichen
    - Lichter
    - Schallsignale
    - Notsignale
    - Vorfahrtsregeln

motorboot:
    - Motorboot
    - Bootstypen
    - Der Motor
    - Der Propeller
    - Steuerung
    - Sicherheit
    - Fahrtheorie
    - Die praktische Prüfung

segelboot:
    - Segelboot
    - Bootstypen
    - Rumpfformen
    - Bug- und Heckformen
    - Takelungsarten
    - Stehendes Gut
    - Laufendes Gut
    - Das Segel
    - Beschläge
    - Koch- & Sanitäreinrichtung
    - Leinen
    - Segeltheorie
    - Segelpraxis
    - Die praktische Prüfung

notAvailable:
    - Navigation
    - Rumpfformen
    - /bug-und-heckformen
    - Takelungsarten
    - Stehendes Gut
    - Laufendes Gut
    - Koch- & Sanitäreinrichtung
    - Leinen
    - Segeltheorie
    - Segelpraxis
    - Segelbootstypen
    - Der Motor
    - Steuerung
    - Fahrtheorie